using System;
using System.Collections.Generic;
using System.Text;

namespace Selenium_Skyscanner
{
    public static class Airports_FlightsFromDotCom
    {
        public static Airport GetAberdeenAirport()
        {
            Airport airport = new Airport("ABZ", "Dyce");
            airport.AddDestinationAirport(new Airport("ALC", "Alicante"));
            airport.AddDestinationAirport(new Airport("AMS", "Amsterdam"));
            airport.AddDestinationAirport(new Airport("BHD", "Belfast"));
            airport.AddDestinationAirport(new Airport("BGO", "Bergen"));
            airport.AddDestinationAirport(new Airport("BHX", "Birmingham"));
            airport.AddDestinationAirport(new Airport("BOJ", "Bourgas"));
            airport.AddDestinationAirport(new Airport("BRS", "Bristol"));
            airport.AddDestinationAirport(new Airport("CPH", "Copenhagen"));
            airport.AddDestinationAirport(new Airport("MME", "Darlington"));
            airport.AddDestinationAirport(new Airport("DUB", "Dublin"));
            airport.AddDestinationAirport(new Airport("EBJ", "Esbjerg"));
            airport.AddDestinationAirport(new Airport("FAO", "Faro"));
            airport.AddDestinationAirport(new Airport("GDN", "Gdansk"));
            airport.AddDestinationAirport(new Airport("GVA", "Geneva"));
            airport.AddDestinationAirport(new Airport("HUY", "Humberside"));
            airport.AddDestinationAirport(new Airport("INV", "Inverness"));
            airport.AddDestinationAirport(new Airport("KOI", "Kirkwall"));
            airport.AddDestinationAirport(new Airport("LHR", "London"));
            airport.AddDestinationAirport(new Airport("LTN", "London"));
            airport.AddDestinationAirport(new Airport("AGP", "Malaga"));
            airport.AddDestinationAirport(new Airport("MAN", "Manchester"));
            airport.AddDestinationAirport(new Airport("NCL", "Newcastle"));
            airport.AddDestinationAirport(new Airport("NWI", "Norwich"));
            airport.AddDestinationAirport(new Airport("OSL", "Oslo"));
            airport.AddDestinationAirport(new Airport("CDG", "Paris"));
            airport.AddDestinationAirport(new Airport("RIX", "Riga"));
            airport.AddDestinationAirport(new Airport("SVG", "Stavanger"));
            airport.AddDestinationAirport(new Airport("LSI", "Sumburgh"));
            return airport;
        }
        
        public static Airport GetGlasgowAirport()
        {
            Airport airport = new Airport("GLA", "Glasgow");
            airport.AddDestinationAirport(new Airport("ALC", "Alicante"));
            airport.AddDestinationAirport(new Airport("LEI", "Almeria"));
            airport.AddDestinationAirport(new Airport("AMS", "Amsterdam"));
            airport.AddDestinationAirport(new Airport("AYT", "Antalya"));
            airport.AddDestinationAirport(new Airport("BEB", "Balivanich"));
            airport.AddDestinationAirport(new Airport("BCN", "Barcelona"));
            airport.AddDestinationAirport(new Airport("BRR", "Barra"));
            airport.AddDestinationAirport(new Airport("BFS", "Belfast"));
            airport.AddDestinationAirport(new Airport("BHD", "Belfast"));
            airport.AddDestinationAirport(new Airport("BER", "Berlin"));
            airport.AddDestinationAirport(new Airport("BHX", "Birmingham"));
            airport.AddDestinationAirport(new Airport("BJV", "Bodrum"));
            airport.AddDestinationAirport(new Airport("BOD", "Bordeaux"));
            airport.AddDestinationAirport(new Airport("BOJ", "Bourgas"));
            airport.AddDestinationAirport(new Airport("BRS", "Bristol"));
            airport.AddDestinationAirport(new Airport("BUD", "Budapest"));
            airport.AddDestinationAirport(new Airport("CAL", "Campbeltown"));
            airport.AddDestinationAirport(new Airport("ORK", "Cork"));
            airport.AddDestinationAirport(new Airport("DLM", "Dalaman"));
            airport.AddDestinationAirport(new Airport("CFN", "Donegal"));
            airport.AddDestinationAirport(new Airport("DXB", "Dubai"));
            airport.AddDestinationAirport(new Airport("DUB", "Dublin"));
            airport.AddDestinationAirport(new Airport("DBV", "Dubrovnik"));
            airport.AddDestinationAirport(new Airport("FAO", "Faro"));
            airport.AddDestinationAirport(new Airport("FRA", "Frankfurt"));
            airport.AddDestinationAirport(new Airport("FUE", "Fuerteventura"));
            airport.AddDestinationAirport(new Airport("FNC", "Funchal"));
            airport.AddDestinationAirport(new Airport("GVA", "Geneva"));
            airport.AddDestinationAirport(new Airport("GRO", "Gerona"));
            airport.AddDestinationAirport(new Airport("ILY", "Glenegedale"));
            airport.AddDestinationAirport(new Airport("YHZ", "Halifax"));
            airport.AddDestinationAirport(new Airport("HER", "Heraklion"));
            airport.AddDestinationAirport(new Airport("IBZ", "Ibiza"));
            airport.AddDestinationAirport(new Airport("ADB", "Izmir"));
            airport.AddDestinationAirport(new Airport("EFL", "Kefalonia"));
            airport.AddDestinationAirport(new Airport("KEF", "Keflavik"));
            airport.AddDestinationAirport(new Airport("KOI", "Kirkwall"));
            airport.AddDestinationAirport(new Airport("CFU", "Korfu"));
            airport.AddDestinationAirport(new Airport("KGS", "Kos"));
            airport.AddDestinationAirport(new Airport("KRK", "Krakow"));
            airport.AddDestinationAirport(new Airport("ACE", "Lanzarote"));
            airport.AddDestinationAirport(new Airport("LCA", "Larnaca"));
            airport.AddDestinationAirport(new Airport("LPA", "Las Palmas"));
            airport.AddDestinationAirport(new Airport("LCY", "London"));
            airport.AddDestinationAirport(new Airport("LGW", "London"));
            airport.AddDestinationAirport(new Airport("LHR", "London"));
            airport.AddDestinationAirport(new Airport("LTN", "London"));
            airport.AddDestinationAirport(new Airport("STN", "London"));
            airport.AddDestinationAirport(new Airport("LDY", "Londonderry"));
            airport.AddDestinationAirport(new Airport("AGP", "Malaga"));
            airport.AddDestinationAirport(new Airport("MAN", "Manchester"));
            airport.AddDestinationAirport(new Airport("MRS", "Marseille"));
            airport.AddDestinationAirport(new Airport("MAH", "Menorca"));
            airport.AddDestinationAirport(new Airport("NAP", "Naples"));
            airport.AddDestinationAirport(new Airport("EWR", "Newark"));
            airport.AddDestinationAirport(new Airport("EMA", "Nottingham"));
            airport.AddDestinationAirport(new Airport("MCO", "Orlando"));
            airport.AddDestinationAirport(new Airport("PMI", "Palma De Mallorca"));
            airport.AddDestinationAirport(new Airport("PFO", "Paphos"));
            airport.AddDestinationAirport(new Airport("CDG", "Paris"));
            airport.AddDestinationAirport(new Airport("PRG", "Prague"));
            airport.AddDestinationAirport(new Airport("PUY", "Pula"));
            airport.AddDestinationAirport(new Airport("REU", "Reus"));
            airport.AddDestinationAirport(new Airport("RHO", "Rhodes"));
            airport.AddDestinationAirport(new Airport("FCO", "Rome"));
            airport.AddDestinationAirport(new Airport("JER", "Saint Peter"));
            airport.AddDestinationAirport(new Airport("SOU", "Southampton"));
            airport.AddDestinationAirport(new Airport("SPU", "Split"));
            airport.AddDestinationAirport(new Airport("SYY", "Stornoway"));
            airport.AddDestinationAirport(new Airport("LSI", "Sumburgh"));
            airport.AddDestinationAirport(new Airport("TFS", "Tenerife"));
            airport.AddDestinationAirport(new Airport("TRE", "Tiree"));
            airport.AddDestinationAirport(new Airport("YYZ", "Toronto"));
            airport.AddDestinationAirport(new Airport("MLA", "Valletta"));
            airport.AddDestinationAirport(new Airport("VCE", "Venice"));
            airport.AddDestinationAirport(new Airport("VIE", "Vienna"));
            airport.AddDestinationAirport(new Airport("WMI", "Warsaw"));
            airport.AddDestinationAirport(new Airport("WRO", "Wroclaw"));
            airport.AddDestinationAirport(new Airport("ZTH", "Zakynthos"));
            return airport;
        }

        public static Airport GetBourgasAirport()
        {
            Airport airport = new Airport("BOJ", "Bourgas");
            airport.AddDestinationAirport(new Airport("ABZ", "Aberdeen"));
            airport.AddDestinationAirport(new Airport("AMS", "Amsterdam"));
            airport.AddDestinationAirport(new Airport("BFS", "Belfast"));
            airport.AddDestinationAirport(new Airport("BLL", "Billund"));
            airport.AddDestinationAirport(new Airport("BHX", "Birmingham"));
            airport.AddDestinationAirport(new Airport("BTS", "Bratislava"));
            airport.AddDestinationAirport(new Airport("BRS", "Bristol"));
            airport.AddDestinationAirport(new Airport("BRU", "Brussels"));
            airport.AddDestinationAirport(new Airport("BUD", "Budapest"));
            airport.AddDestinationAirport(new Airport("CWL", "Cardiff"));
            airport.AddDestinationAirport(new Airport("CPH", "Copenhagen"));
            airport.AddDestinationAirport(new Airport("MME", "Darlington"));
            airport.AddDestinationAirport(new Airport("DNK", "Dnepropetrovsk"));
            airport.AddDestinationAirport(new Airport("DSA", "Doncaster"));
            airport.AddDestinationAirport(new Airport("DUB", "Dublin"));
            airport.AddDestinationAirport(new Airport("DUS", "Dusseldorf"));
            airport.AddDestinationAirport(new Airport("EDI", "Edinburgh"));
            airport.AddDestinationAirport(new Airport("GDN", "Gdansk"));
            airport.AddDestinationAirport(new Airport("GLA", "Glasgow"));
            airport.AddDestinationAirport(new Airport("HAM", "Hamburg"));
            airport.AddDestinationAirport(new Airport("HEL", "Helsinki"));
            airport.AddDestinationAirport(new Airport("HUY", "Humberside"));
            airport.AddDestinationAirport(new Airport("KTW", "Katowice"));
            airport.AddDestinationAirport(new Airport("KBP", "Kiev"));
            airport.AddDestinationAirport(new Airport("KRK", "Krakow"));
            airport.AddDestinationAirport(new Airport("LBA", "Leeds"));
            airport.AddDestinationAirport(new Airport("LGW", "London"));
            airport.AddDestinationAirport(new Airport("LTN", "London"));
            airport.AddDestinationAirport(new Airport("STN", "London"));
            airport.AddDestinationAirport(new Airport("MAN", "Manchester"));
            airport.AddDestinationAirport(new Airport("DME", "Moscow"));
            airport.AddDestinationAirport(new Airport("SVO", "Moscow"));
            airport.AddDestinationAirport(new Airport("NCL", "Newcastle"));
            airport.AddDestinationAirport(new Airport("NWI", "Norwich"));
            airport.AddDestinationAirport(new Airport("EMA", "Nottingham"));
            airport.AddDestinationAirport(new Airport("OSR", "Ostrava"));
            airport.AddDestinationAirport(new Airport("PRG", "Prague"));
            airport.AddDestinationAirport(new Airport("LED", "Sankt Petersburg"));
            airport.AddDestinationAirport(new Airport("SOF", "Sofia"));
            airport.AddDestinationAirport(new Airport("STR", "Stuttgart"));
            airport.AddDestinationAirport(new Airport("TLV", "Tel Aviv"));
            airport.AddDestinationAirport(new Airport("BRQ", "Turany"));
            airport.AddDestinationAirport(new Airport("VAR", "Varna"));
            airport.AddDestinationAirport(new Airport("VIE", "Vienna"));
            airport.AddDestinationAirport(new Airport("WAW", "Warsaw"));
            airport.AddDestinationAirport(new Airport("WMI", "Warsaw"));
            return airport;
        }

        public static Airport GetVarnaAirport()
        {
            Airport airport = new Airport("VAR", "Varna");
            airport.AddDestinationAirport(new Airport("ATH", "Athens"));
            airport.AddDestinationAirport(new Airport("BCN", "Barcelona"));
            airport.AddDestinationAirport(new Airport("BGY", "Bergamo"));
            airport.AddDestinationAirport(new Airport("BER", "Berlin"));
            airport.AddDestinationAirport(new Airport("SXF", "Berlin"));
            airport.AddDestinationAirport(new Airport("BOJ", "Bourgas"));
            airport.AddDestinationAirport(new Airport("BRE", "Bremen"));
            airport.AddDestinationAirport(new Airport("CRL", "Brussels"));
            airport.AddDestinationAirport(new Airport("CGN", "Cologne"));
            airport.AddDestinationAirport(new Airport("DTM", "Dortmund"));
            airport.AddDestinationAirport(new Airport("DUS", "Dusseldorf"));
            airport.AddDestinationAirport(new Airport("EIN", "Eindhoven"));
            airport.AddDestinationAirport(new Airport("ERF", "Erfurt"));
            airport.AddDestinationAirport(new Airport("FRA", "Frankfurt"));
            airport.AddDestinationAirport(new Airport("GRZ", "Graz"));
            airport.AddDestinationAirport(new Airport("HHN", "Hahn"));
            airport.AddDestinationAirport(new Airport("HAM", "Hamburg"));
            airport.AddDestinationAirport(new Airport("HAJ", "Hanover"));
            airport.AddDestinationAirport(new Airport("HEL", "Helsinki"));
            airport.AddDestinationAirport(new Airport("IST", "Istanbul"));
            airport.AddDestinationAirport(new Airport("FKB", "Karlsruhe"));
            airport.AddDestinationAirport(new Airport("LCA", "Larnaca"));
            airport.AddDestinationAirport(new Airport("LEJ", "Leipzig"));
            airport.AddDestinationAirport(new Airport("LPL", "Liverpool"));
            airport.AddDestinationAirport(new Airport("LCJ", "Lodz"));
            airport.AddDestinationAirport(new Airport("LGW", "London"));
            airport.AddDestinationAirport(new Airport("LTN", "London"));
            airport.AddDestinationAirport(new Airport("LUX", "Luxemburg"));
            airport.AddDestinationAirport(new Airport("MAN", "Manchester"));
            airport.AddDestinationAirport(new Airport("FMM", "Memmingen"));
            airport.AddDestinationAirport(new Airport("DME", "Moscow"));
            airport.AddDestinationAirport(new Airport("FMO", "Muenster"));
            airport.AddDestinationAirport(new Airport("MUC", "Munich"));
            airport.AddDestinationAirport(new Airport("NTE", "Nantes"));
            airport.AddDestinationAirport(new Airport("NUE", "Nuremberg"));
            airport.AddDestinationAirport(new Airport("PRG", "Prague"));
            airport.AddDestinationAirport(new Airport("SZG", "Salzburg"));
            airport.AddDestinationAirport(new Airport("SOF", "Sofia"));
            airport.AddDestinationAirport(new Airport("STR", "Stuttgart"));
            airport.AddDestinationAirport(new Airport("TLV", "Tel Aviv"));
            airport.AddDestinationAirport(new Airport("VIE", "Vienna"));
            airport.AddDestinationAirport(new Airport("WAW", "Warsaw"));
            airport.AddDestinationAirport(new Airport("ZRH", "Zurich"));
            return airport;
        }

        public static Airport GetEdinburghAirport()
        {
            Airport ediAirport = new Airport("EDI", "Edinburgh");
            ediAirport.AddDestinationAirport(new Airport("ALC", "Alicante"));
            ediAirport.AddDestinationAirport(new Airport("AMS", "Amsterdam"));
            ediAirport.AddDestinationAirport(new Airport("AYT", "Antalya"));
            ediAirport.AddDestinationAirport(new Airport("ATH", "Athens"));
            ediAirport.AddDestinationAirport(new Airport("BCN", "Barcelona"));
            ediAirport.AddDestinationAirport(new Airport("BSL", "Basel"));
            ediAirport.AddDestinationAirport(new Airport("BFS", "Belfast"));
            ediAirport.AddDestinationAirport(new Airport("BHD", "Belfast"));
            ediAirport.AddDestinationAirport(new Airport("BGY", "Bergamo"));
            ediAirport.AddDestinationAirport(new Airport("BER", "Berlin"));
            ediAirport.AddDestinationAirport(new Airport("SXF", "Berlin"));
            ediAirport.AddDestinationAirport(new Airport("TXL", "Berlin"));
            ediAirport.AddDestinationAirport(new Airport("BZR", "Beziers"));
            ediAirport.AddDestinationAirport(new Airport("BIO", "Bilbao"));
            ediAirport.AddDestinationAirport(new Airport("BLL", "Billund"));
            ediAirport.AddDestinationAirport(new Airport("BHX", "Birmingham"));
            ediAirport.AddDestinationAirport(new Airport("BJV", "Bodrum"));
            ediAirport.AddDestinationAirport(new Airport("BLQ", "Bologna"));
            ediAirport.AddDestinationAirport(new Airport("BOD", "Bordeaux"));
            ediAirport.AddDestinationAirport(new Airport("BOJ", "Bourgas"));
            ediAirport.AddDestinationAirport(new Airport("BTS", "Bratislava"));
            ediAirport.AddDestinationAirport(new Airport("BRS", "Bristol"));
            ediAirport.AddDestinationAirport(new Airport("BRU", "Brussels"));
            ediAirport.AddDestinationAirport(new Airport("CRL", "Brussels"));
            ediAirport.AddDestinationAirport(new Airport("OTP", "Bucharest"));
            ediAirport.AddDestinationAirport(new Airport("BUD", "Budapest"));
            ediAirport.AddDestinationAirport(new Airport("BZG", "Bydgoszcz"));
            ediAirport.AddDestinationAirport(new Airport("CCF", "Carcassonne"));
            ediAirport.AddDestinationAirport(new Airport("CTA", "Catania"));
            ediAirport.AddDestinationAirport(new Airport("ORD", "Chicago"));
            ediAirport.AddDestinationAirport(new Airport("CGN", "Cologne"));
            ediAirport.AddDestinationAirport(new Airport("CPH", "Copenhagen"));
            ediAirport.AddDestinationAirport(new Airport("ORK", "Cork"));
            ediAirport.AddDestinationAirport(new Airport("DLM", "Dalaman"));
            ediAirport.AddDestinationAirport(new Airport("DOH", "Doha"));
            ediAirport.AddDestinationAirport(new Airport("DXB", "Dubai"));
            ediAirport.AddDestinationAirport(new Airport("DUB", "Dublin"));
            ediAirport.AddDestinationAirport(new Airport("DBV", "Dubrovnik"));
            ediAirport.AddDestinationAirport(new Airport("DUS", "Dusseldorf"));
            ediAirport.AddDestinationAirport(new Airport("EIN", "Eindhoven"));
            ediAirport.AddDestinationAirport(new Airport("EXT", "Exeter"));
            ediAirport.AddDestinationAirport(new Airport("FAO", "Faro"));
            ediAirport.AddDestinationAirport(new Airport("FLR", "Firenze"));
            ediAirport.AddDestinationAirport(new Airport("FRA", "Frankfurt"));
            ediAirport.AddDestinationAirport(new Airport("FUE", "Fuerteventura"));
            ediAirport.AddDestinationAirport(new Airport("FNC", "Funchal"));
            ediAirport.AddDestinationAirport(new Airport("GDN", "Gdansk"));
            ediAirport.AddDestinationAirport(new Airport("GVA", "Geneva"));
            ediAirport.AddDestinationAirport(new Airport("GRO", "Gerona"));
            ediAirport.AddDestinationAirport(new Airport("GIB", "Gibraltar"));
            ediAirport.AddDestinationAirport(new Airport("GOT", "Gothenburg"));
            ediAirport.AddDestinationAirport(new Airport("GNB", "Grenoble"));
            ediAirport.AddDestinationAirport(new Airport("HAM", "Hamburg"));
            ediAirport.AddDestinationAirport(new Airport("HEL", "Helsinki"));
            ediAirport.AddDestinationAirport(new Airport("HER", "Heraklion"));
            ediAirport.AddDestinationAirport(new Airport("IBZ", "Ibiza"));
            ediAirport.AddDestinationAirport(new Airport("IST", "Istanbul"));
            ediAirport.AddDestinationAirport(new Airport("ADB", "Izmir"));
            ediAirport.AddDestinationAirport(new Airport("FKB", "Karlsruhe"));
            ediAirport.AddDestinationAirport(new Airport("KTW", "Katowice"));
            ediAirport.AddDestinationAirport(new Airport("KUN", "Kaunas"));
            ediAirport.AddDestinationAirport(new Airport("KEF", "Keflavik"));
            ediAirport.AddDestinationAirport(new Airport("KOI", "Kirkwall"));
            ediAirport.AddDestinationAirport(new Airport("CFU", "Korfu"));
            ediAirport.AddDestinationAirport(new Airport("KGS", "Kos"));
            ediAirport.AddDestinationAirport(new Airport("KRK", "Krakow"));
            ediAirport.AddDestinationAirport(new Airport("ACE", "Lanzarote"));
            ediAirport.AddDestinationAirport(new Airport("LCA", "Larnaca"));
            ediAirport.AddDestinationAirport(new Airport("LPA", "Las Palmas"));
            ediAirport.AddDestinationAirport(new Airport("LIS", "Lisbon"));
            ediAirport.AddDestinationAirport(new Airport("LCY", "London"));
            ediAirport.AddDestinationAirport(new Airport("LGW", "London"));
            ediAirport.AddDestinationAirport(new Airport("LHR", "London"));
            ediAirport.AddDestinationAirport(new Airport("LTN", "London"));
            ediAirport.AddDestinationAirport(new Airport("STN", "London"));
            ediAirport.AddDestinationAirport(new Airport("LDY", "Londonderry"));
            ediAirport.AddDestinationAirport(new Airport("LYS", "Lyon"));
            ediAirport.AddDestinationAirport(new Airport("MAD", "Madrid"));
            ediAirport.AddDestinationAirport(new Airport("AGP", "Malaga"));
            ediAirport.AddDestinationAirport(new Airport("MRS", "Marseille"));
            ediAirport.AddDestinationAirport(new Airport("FMM", "Memmingen"));
            ediAirport.AddDestinationAirport(new Airport("MAH", "Menorca"));
            ediAirport.AddDestinationAirport(new Airport("MXP", "Milano"));
            ediAirport.AddDestinationAirport(new Airport("MUC", "Munich"));
            ediAirport.AddDestinationAirport(new Airport("NTE", "Nantes"));
            ediAirport.AddDestinationAirport(new Airport("NAP", "Naples"));
            ediAirport.AddDestinationAirport(new Airport("JFK", "New York"));
            ediAirport.AddDestinationAirport(new Airport("EWR", "Newark"));
            ediAirport.AddDestinationAirport(new Airport("NCE", "Nice"));
            ediAirport.AddDestinationAirport(new Airport("NWI", "Norwich"));
            ediAirport.AddDestinationAirport(new Airport("EMA", "Nottingham"));
            ediAirport.AddDestinationAirport(new Airport("OSL", "Oslo"));
            ediAirport.AddDestinationAirport(new Airport("PMI", "Palma De Mallorca"));
            ediAirport.AddDestinationAirport(new Airport("PFO", "Paphos"));
            ediAirport.AddDestinationAirport(new Airport("CDG", "Paris"));
            ediAirport.AddDestinationAirport(new Airport("PHL", "Philadelphia"));
            ediAirport.AddDestinationAirport(new Airport("PSA", "Pisa"));
            ediAirport.AddDestinationAirport(new Airport("POZ", "Poznan"));
            ediAirport.AddDestinationAirport(new Airport("PRG", "Prague"));
            ediAirport.AddDestinationAirport(new Airport("PUY", "Pula"));
            ediAirport.AddDestinationAirport(new Airport("REU", "Reus"));
            ediAirport.AddDestinationAirport(new Airport("RHO", "Rhodes"));
            ediAirport.AddDestinationAirport(new Airport("RIX", "Riga"));
            ediAirport.AddDestinationAirport(new Airport("CIA", "Rome"));
            ediAirport.AddDestinationAirport(new Airport("IOM", "Ronaldsway"));
            ediAirport.AddDestinationAirport(new Airport("RTM", "Rotterdam"));
            ediAirport.AddDestinationAirport(new Airport("JER", "Saint Peter"));
            ediAirport.AddDestinationAirport(new Airport("SZG", "Salzburg"));
            ediAirport.AddDestinationAirport(new Airport("SDR", "Santander"));
            ediAirport.AddDestinationAirport(new Airport("SVQ", "Sevilla"));
            ediAirport.AddDestinationAirport(new Airport("SNN", "Shannon"));
            ediAirport.AddDestinationAirport(new Airport("SOF", "Sofia"));
            ediAirport.AddDestinationAirport(new Airport("SOU", "Southampton"));
            ediAirport.AddDestinationAirport(new Airport("SPU", "Split"));
            ediAirport.AddDestinationAirport(new Airport("SVG", "Stavanger"));
            ediAirport.AddDestinationAirport(new Airport("ARN", "Stockholm"));
            ediAirport.AddDestinationAirport(new Airport("SYY", "Stornoway"));
            ediAirport.AddDestinationAirport(new Airport("STR", "Stuttgart"));
            ediAirport.AddDestinationAirport(new Airport("LSI", "Sumburgh"));
            ediAirport.AddDestinationAirport(new Airport("TLL", "Tallinn"));
            ediAirport.AddDestinationAirport(new Airport("TFS", "Tenerife"));
            ediAirport.AddDestinationAirport(new Airport("SKG", "Thessaloniki"));
            ediAirport.AddDestinationAirport(new Airport("YYZ", "Toronto"));
            ediAirport.AddDestinationAirport(new Airport("FAE", "Torshavn"));
            ediAirport.AddDestinationAirport(new Airport("TLS", "Toulouse"));
            ediAirport.AddDestinationAirport(new Airport("TSF", "Treviso"));
            ediAirport.AddDestinationAirport(new Airport("VLC", "Valencia"));
            ediAirport.AddDestinationAirport(new Airport("MLA", "Valletta"));
            ediAirport.AddDestinationAirport(new Airport("VCE", "Venice"));
            ediAirport.AddDestinationAirport(new Airport("VRN", "Verona"));
            ediAirport.AddDestinationAirport(new Airport("VIE", "Vienna"));
            ediAirport.AddDestinationAirport(new Airport("WAW", "Warsaw"));
            ediAirport.AddDestinationAirport(new Airport("WMI", "Warsaw"));
            ediAirport.AddDestinationAirport(new Airport("IAD", "Washington"));
            ediAirport.AddDestinationAirport(new Airport("NRN", "Weeze"));
            ediAirport.AddDestinationAirport(new Airport("WRO", "Wroclaw"));
            ediAirport.AddDestinationAirport(new Airport("ZTH", "Zakynthos"));
            ediAirport.AddDestinationAirport(new Airport("ZRH", "Zurich"));
            return ediAirport;
        }

        public static Airport GetSofiaAirport()
        {
            Airport sofiaAirport = new Airport("SOF", "Sofia");
            sofiaAirport.AddDestinationAirport(new Airport("AUH", "Abu Dhabi"));
            sofiaAirport.AddDestinationAirport(new Airport("ALC", "Alicante"));
            sofiaAirport.AddDestinationAirport(new Airport("AMS", "Amsterdam"));
            sofiaAirport.AddDestinationAirport(new Airport("AQJ", "Aqaba"));
            sofiaAirport.AddDestinationAirport(new Airport("ATH", "Athens"));
            sofiaAirport.AddDestinationAirport(new Airport("BCN", "Barcelona"));
            sofiaAirport.AddDestinationAirport(new Airport("BRI", "Bari"));
            sofiaAirport.AddDestinationAirport(new Airport("BSL", "Basel"));
            sofiaAirport.AddDestinationAirport(new Airport("BVA", "Beauvais"));
            sofiaAirport.AddDestinationAirport(new Airport("BEG", "Beograd"));
            sofiaAirport.AddDestinationAirport(new Airport("BGY", "Bergamo"));
            sofiaAirport.AddDestinationAirport(new Airport("BER", "Berlin"));
            sofiaAirport.AddDestinationAirport(new Airport("SXF", "Berlin"));
            sofiaAirport.AddDestinationAirport(new Airport("TXL", "Berlin"));
            sofiaAirport.AddDestinationAirport(new Airport("BLL", "Billund"));
            sofiaAirport.AddDestinationAirport(new Airport("BHX", "Birmingham"));
            sofiaAirport.AddDestinationAirport(new Airport("BLQ", "Bologna"));
            sofiaAirport.AddDestinationAirport(new Airport("BOJ", "Bourgas"));
            sofiaAirport.AddDestinationAirport(new Airport("BTS", "Bratislava"));
            sofiaAirport.AddDestinationAirport(new Airport("BRS", "Bristol"));
            sofiaAirport.AddDestinationAirport(new Airport("BRU", "Brussels"));
            sofiaAirport.AddDestinationAirport(new Airport("CRL", "Brussels"));
            sofiaAirport.AddDestinationAirport(new Airport("OTP", "Bucharest"));
            sofiaAirport.AddDestinationAirport(new Airport("BUD", "Budapest"));
            sofiaAirport.AddDestinationAirport(new Airport("CTA", "Catania"));
            sofiaAirport.AddDestinationAirport(new Airport("CHQ", "Chania"));
            sofiaAirport.AddDestinationAirport(new Airport("CGN", "Cologne"));
            sofiaAirport.AddDestinationAirport(new Airport("CPH", "Copenhagen"));
            sofiaAirport.AddDestinationAirport(new Airport("DOH", "Doha"));
            sofiaAirport.AddDestinationAirport(new Airport("DTM", "Dortmund"));
            sofiaAirport.AddDestinationAirport(new Airport("DXB", "Dubai"));
            sofiaAirport.AddDestinationAirport(new Airport("DUB", "Dublin"));
            sofiaAirport.AddDestinationAirport(new Airport("DUS", "Dusseldorf"));
            sofiaAirport.AddDestinationAirport(new Airport("EDI", "Edinburgh"));
            sofiaAirport.AddDestinationAirport(new Airport("ETM", "Eilat"));
            sofiaAirport.AddDestinationAirport(new Airport("EIN", "Eindhoven"));
            sofiaAirport.AddDestinationAirport(new Airport("FRA", "Frankfurt"));
            sofiaAirport.AddDestinationAirport(new Airport("GVA", "Geneva"));
            sofiaAirport.AddDestinationAirport(new Airport("HHN", "Hahn"));
            sofiaAirport.AddDestinationAirport(new Airport("HAM", "Hamburg"));
            sofiaAirport.AddDestinationAirport(new Airport("HRG", "Hurghada"));
            sofiaAirport.AddDestinationAirport(new Airport("IST", "Istanbul"));
            sofiaAirport.AddDestinationAirport(new Airport("FKB", "Karlsruhe"));
            sofiaAirport.AddDestinationAirport(new Airport("KBP", "Kiev"));
            sofiaAirport.AddDestinationAirport(new Airport("LCA", "Larnaca"));
            sofiaAirport.AddDestinationAirport(new Airport("LIS", "Lisbon"));
            sofiaAirport.AddDestinationAirport(new Airport("LPL", "Liverpool"));
            sofiaAirport.AddDestinationAirport(new Airport("LGW", "London"));
            sofiaAirport.AddDestinationAirport(new Airport("LHR", "London"));
            sofiaAirport.AddDestinationAirport(new Airport("LTN", "London"));
            sofiaAirport.AddDestinationAirport(new Airport("STN", "London"));
            sofiaAirport.AddDestinationAirport(new Airport("MAD", "Madrid"));
            sofiaAirport.AddDestinationAirport(new Airport("AGP", "Malaga"));
            sofiaAirport.AddDestinationAirport(new Airport("MAN", "Manchester"));
            sofiaAirport.AddDestinationAirport(new Airport("FMM", "Memmingen"));
            sofiaAirport.AddDestinationAirport(new Airport("MXP", "Milano"));
            sofiaAirport.AddDestinationAirport(new Airport("SVO", "Moscow"));
            sofiaAirport.AddDestinationAirport(new Airport("MUC", "Munich"));
            sofiaAirport.AddDestinationAirport(new Airport("JMK", "Mykonos"));
            sofiaAirport.AddDestinationAirport(new Airport("NAP", "Naples"));
            sofiaAirport.AddDestinationAirport(new Airport("NCE", "Nice"));
            sofiaAirport.AddDestinationAirport(new Airport("EMA", "Nottingham"));
            sofiaAirport.AddDestinationAirport(new Airport("PMI", "Palma De Mallorca"));
            sofiaAirport.AddDestinationAirport(new Airport("CDG", "Paris"));
            sofiaAirport.AddDestinationAirport(new Airport("PRG", "Prague"));
            sofiaAirport.AddDestinationAirport(new Airport("CIA", "Rome"));
            sofiaAirport.AddDestinationAirport(new Airport("FCO", "Rome"));
            sofiaAirport.AddDestinationAirport(new Airport("LED", "Sankt Petersburg"));
            sofiaAirport.AddDestinationAirport(new Airport("SSH", "Sharm El-Sheikh"));
            sofiaAirport.AddDestinationAirport(new Airport("STR", "Stuttgart"));
            sofiaAirport.AddDestinationAirport(new Airport("TLV", "Tel Aviv"));
            sofiaAirport.AddDestinationAirport(new Airport("TSF", "Treviso"));
            sofiaAirport.AddDestinationAirport(new Airport("VLC", "Valencia"));
            sofiaAirport.AddDestinationAirport(new Airport("MLA", "Valletta"));
            sofiaAirport.AddDestinationAirport(new Airport("VAR", "Varna"));
            sofiaAirport.AddDestinationAirport(new Airport("VIE", "Vienna"));
            sofiaAirport.AddDestinationAirport(new Airport("WAW", "Warsaw"));
            sofiaAirport.AddDestinationAirport(new Airport("ZRH", "Zurich"));
            return sofiaAirport;
        }
    }
}
